# v0.3.0
# { "Depends": "py-genlayer:5jycge4q8k23462jtb0b9fyey1s9qz928sz2nbrd9mg4sxqg2qng" }
"""Generated by deploy/build_bundle.py from contracts/conditions.py and contracts/warrant.py.
Comments removed to keep the deploy small; read them in those files."""
READ = 'read'
_MAX_PATH = 64

def valid_field_path(path: str) -> bool:
    if not path or len(path) > _MAX_PATH:
        return False
    if path.startswith('.') or path.endswith('.') or '..' in path:
        return False
    for ch in path:
        if not ('0' <= ch <= '9' or 'a' <= ch <= 'z' or 'A' <= ch <= 'Z' or (ch in '._-')):
            return False
    return True
OPS = ('eq', 'ne', 'ge', 'gt', 'le', 'lt')

def compare(op: str, value: str, want: str) -> bool:
    if op not in OPS:
        raise ValueError('unknown comparison: ' + repr(op))
    if op == 'eq':
        return value == want
    if op == 'ne':
        return value != want
    if not _is_int(value) or not _is_int(want):
        return False
    left, right = (int(value), int(want))
    if op == 'ge':
        return left >= right
    if op == 'gt':
        return left > right
    if op == 'le':
        return left <= right
    return left < right

def _is_int(text: str) -> bool:
    t = (text or '').strip()
    if t.startswith('-'):
        t = t[1:]
    return bool(t) and t.isdigit() and t.isascii()
MAX_CONDITIONS = 3

def parse_conditions(text: str) -> list:
    out = []
    for raw in (text or '').split(';'):
        clause = raw.strip()
        if not clause:
            continue
        parts = clause.split()
        if len(parts) < 3:
            raise ValueError('a condition reads: field op value, not ' + repr(clause))
        field, op = (parts[0], parts[1])
        want = ' '.join(parts[2:])
        if not valid_field_path(field):
            raise ValueError('bad field path in condition: ' + repr(field))
        if op not in OPS:
            raise ValueError('unknown comparison: ' + repr(op))
        if any((field == f and op == o for f, o, _ in out)):
            raise ValueError('the same field and comparison twice: ' + repr(clause))
        out.append((field, op, want))
    if not out:
        raise ValueError('a deal needs at least one condition')
    if len(out) > MAX_CONDITIONS:
        raise ValueError(f'at most {MAX_CONDITIONS} conditions per deal')
    return out

def join_conditions(conditions: list) -> str:
    return '; '.join((f'{field} {op} {want}' for field, op, want in conditions))

def evaluate(conditions: list, values: dict) -> dict:
    saw = []
    for field, op, want in conditions:
        value = str(values[field]) if field in values else ''
        saw.append(value)
        if not compare(op, value, want):
            return {'ok': False, 'saw': saw, 'why': f"{field} is {value or 'empty'}, which is not {op} {want}"}
    return {'ok': True, 'saw': saw, 'why': ''}
SETTLING_SECONDS = 3600

def epoch_seconds(stamp: str):
    s = (stamp or '').strip()
    if len(s) < 19 or s[4] != '-' or s[7] != '-' or (s[10] != 'T') or (s[13] != ':') or (s[16] != ':'):
        return None
    for i in (0, 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18):
        if not '0' <= s[i] <= '9':
            return None
    year, month, day = (int(s[0:4]), int(s[5:7]), int(s[8:10]))
    hour, minute, second = (int(s[11:13]), int(s[14:16]), int(s[17:19]))
    if not 1 <= month <= 12 or day < 1 or day > _days_in_month(year, month):
        return None
    if hour > 23 or minute > 59 or second > 60:
        return None
    return _days_from_civil(year, month, day) * 86400 + hour * 3600 + minute * 60 + second

def _days_in_month(year: int, month: int) -> int:
    if month == 2:
        leap = year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
        return 29 if leap else 28
    return 30 if month in (4, 6, 9, 11) else 31

def _days_from_civil(year: int, month: int, day: int) -> int:
    y = year - (1 if month <= 2 else 0)
    era = (y if y >= 0 else y - 399) // 400
    year_of_era = y - era * 400
    day_of_year = (153 * (month + (-3 if month > 2 else 9)) + 2) // 5 + day - 1
    day_of_era = year_of_era * 365 + year_of_era // 4 - year_of_era // 100 + day_of_year
    return era * 146097 + day_of_era - 719468
from dataclasses import dataclass
import genlayer as gl
from genlayer.types import *
STATE_OPEN = 'open'
STATE_PAID = 'paid'
STATE_REFUNDED = 'refunded'

@gl.storage.allow
@dataclass
class Deal:
    depositor: Address
    beneficiary: Address
    amount: u256
    signal: Address
    feed: str
    key: str
    conditions: str
    deadline: str
    opened_at: str
    state: str
    decided_at: str
    saw: str
    reason: str

class Warrant(gl.contract.Contract):
    deals: gl.storage.TreeMap[str, Deal]
    deal_ids: gl.storage.DynArray[str]
    committed: u256

    def __init__(self):
        self.committed = 0

    @gl.public.write.payable
    def open_deal(self, name: str, beneficiary: str, signal: str, feed_id: str, key: str, conditions: str, deadline: str) -> dict:
        label = name.strip().lower()
        if not label or len(label) > 40:
            raise gl.vm.UserError('name the deal')
        depositor = gl.message.sender_address
        deal_id = depositor.as_hex.lower() + ':' + label
        if deal_id in self.deals:
            raise gl.vm.UserError('that deal already exists')
        amount = gl.message.value
        if amount <= 0:
            raise gl.vm.UserError('send the deposit with this call')
        try:
            wanted = parse_conditions(conditions)
        except ValueError as bad:
            raise gl.vm.UserError(str(bad))
        day = deadline.strip()
        if not _valid_date(day):
            raise gl.vm.UserError('deadline must be a YYYY-MM-DD date')
        if day <= _today():
            raise gl.vm.UserError('the deadline must be in the future')
        paid_to = _address(beneficiary)
        if paid_to.as_hex.lower() == '0x' + '00' * 20:
            raise gl.vm.UserError('a payout to the zero address would burn the deposit')
        signal_at = _address(signal)
        fid = feed_id.strip().lower()
        try:
            described = gl.contract.get_at(signal_at).view().get_feed(fid)
        except Exception:
            raise gl.vm.UserError('that SIGNAL contract has no feed ' + fid)
        published = [str(f) for f in described['fields']]
        for field, _op, _want in wanted:
            if field not in published:
                raise gl.vm.UserError('that feed does not publish the field ' + field)
        self.deals[deal_id] = Deal(depositor=depositor, beneficiary=paid_to, amount=amount, signal=signal_at, feed=fid, key=key.strip(), conditions=join_conditions(wanted), deadline=day, opened_at=_stamp(), state=STATE_OPEN, decided_at='', saw='', reason='')
        self.deal_ids.append(deal_id)
        self.committed = self.committed + amount
        return _as_dict(deal_id, self.deals[deal_id])

    @gl.public.write
    def release(self, deal_id: str) -> dict:
        key = deal_id.strip().lower()
        if key not in self.deals:
            raise gl.vm.UserError('no such deal: ' + key)
        deal = self.deals[key]
        if deal.state != STATE_OPEN:
            raise gl.vm.UserError(f'deal is already {deal.state}: {key}')
        record = gl.contract.get_at(deal.signal).view().get_reading(deal.feed, deal.key)
        status = str(record['status'])
        if status != READ:
            return self._undecided(key, deal, 'the reading says ' + (status or 'nothing has been read yet'))
        taken = epoch_seconds(str(record['read_at']))
        opened = epoch_seconds(deal.opened_at)
        now = epoch_seconds(_stamp())
        if taken is None or opened is None or now is None:
            return self._undecided(key, deal, 'a timestamp on this deal or reading could not be read')
        if taken <= opened:
            return self._undecided(key, deal, 'the latest reading is older than this deal')
        if now - taken < SETTLING_SECONDS:
            waited = now - taken
            return self._undecided(key, deal, f'the reading is {waited} seconds old and must be {SETTLING_SECONDS} before it can pay')
        verdict = evaluate(parse_conditions(deal.conditions), record['values'])
        if not verdict['ok']:
            return self._undecided(key, deal, str(verdict['why']))
        deal.state = STATE_PAID
        deal.decided_at = _stamp()
        deal.saw = '; '.join((str(v) for v in verdict['saw']))
        deal.reason = 'every condition holds: ' + deal.saw
        self.deals[key] = deal
        self.committed = self.committed - deal.amount
        _pay(deal.beneficiary, int(deal.amount))
        return _as_dict(key, deal)

    @gl.public.write
    def refund(self, deal_id: str) -> dict:
        key = deal_id.strip().lower()
        if key not in self.deals:
            raise gl.vm.UserError('no such deal: ' + key)
        deal = self.deals[key]
        if deal.state != STATE_OPEN:
            raise gl.vm.UserError(f'deal is already {deal.state}: {key}')
        if _today() <= deal.deadline:
            raise gl.vm.UserError('the deadline has not passed yet')
        deal.state = STATE_REFUNDED
        deal.decided_at = _stamp()
        deal.reason = 'the deadline passed without the condition being met'
        self.deals[key] = deal
        self.committed = self.committed - deal.amount
        _pay(deal.depositor, int(deal.amount))
        return _as_dict(key, deal)

    def _undecided(self, key: str, deal: Deal, why: str) -> dict:
        deal.reason = why
        self.deals[key] = deal
        return _as_dict(key, deal)

    @gl.public.view
    def get_deal(self, deal_id: str) -> dict:
        key = deal_id.strip().lower()
        return _as_dict(key, self.deals[key])

    @gl.public.view
    def deal_list(self) -> list:
        return [d for d in self.deal_ids]

    @gl.public.view
    def count(self) -> int:
        return len(self.deal_ids)

    @gl.public.view
    def reserves(self) -> dict:
        return {'committed': str(self.committed)}

def _stamp() -> str:
    return str(gl.message.raw['datetime'])

def _today() -> str:
    return _stamp()[:10]

def _valid_date(day: str) -> bool:
    if len(day) != 10 or day[4] != '-' or day[7] != '-':
        return False
    digits = day[0:4] + day[5:7] + day[8:10]
    for ch in digits:
        if not '0' <= ch <= '9':
            return False
    return '01' <= day[5:7] <= '12' and '01' <= day[8:10] <= '31'

def _address(value) -> Address:
    if hasattr(value, 'as_hex'):
        return value
    return Address(str(value).strip())

@gl.evm.contract_interface
class _Wallet:

    class View:
        pass

    class Write:
        pass

def _pay(to: Address, amount: int) -> None:
    _Wallet(to).emit_transfer(value=amount)

def _as_dict(key: str, deal: Deal) -> dict:
    return {'deal_id': key, 'depositor': deal.depositor.as_hex, 'beneficiary': deal.beneficiary.as_hex, 'amount': str(deal.amount), 'signal': deal.signal.as_hex, 'feed': deal.feed, 'key': deal.key, 'conditions': [{'field': f, 'op': o, 'want': w} for f, o, w in parse_conditions(deal.conditions)], 'deadline': deal.deadline, 'opened_at': deal.opened_at, 'state': deal.state, 'decided_at': deal.decided_at, 'saw': deal.saw, 'reason': deal.reason}
